Write the mass balence for the 3 stage counter current cascade and determine the concentration of contaminant in g/m3.

In [1]:
import numpy as np
import numpy.linalg as nl

A = np.array([[-30.0,20.0,0.0],[10.0,-30.0,20.0],[0.0,10.0,-30.0]])

print(A)

f = np.array([-200.0, 0.0, 0.0])

print(nl.solve(A,f))

[[-30.  20.   0.]
 [ 10. -30.  20.]
 [  0.  10. -30.]]
[9.33333333 4.         1.33333333]
